### ISSUE TITLE
corbarCPLEX does not compile with CPLEX22.11

### ISSUE THREAD

**Issue by Porthmeus** [Waschina/cobrarCPLEX#1]
Hi Silvio,
I just tried to install cobraCPLEX with CPLEX 22.11 and got an error that a header file is missing. I needed to switch to CPLEX 20.1 which worked than. Just wanted to let you know, to fix that in the future maybe. Error message is attached.
[corbarCPLEX_error.txt](https://github.com/user-attachments/files/18180881/corbarCPLEX_error.txt)

**Comment by Waschina** [comment]
Mhh cant reproduce the error, it compiles fine here with cplex 2211.

Which exact command did you use to install cobrarCPLEX?

**Comment by Waschina** [comment]
I just remembered that I had the same error once. The problem was not with cobrarCPLEX but with the ILOG installation. Could you check the installation logs from ILOG?

**Comment by Porthmeus** [comment]
OK nevermind, fresh reinstall of cplex2211 did the trick. Not sure, why the old installation was missing the header file though, as I never touched the directory. Anyways, thanks for the help!
